# SPDX-License-Identifier: GPL-2.0-only
#
# LuCI support for MediaTek Hardware QoS (HQoS)
# Copyright (C) 2026 ImmortalWrt
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for MediaTek Hardware QoS
LUCI_DEPENDS:=+mtk-hqos +luci-base
LUCI_PKGARCH:=all

PKG_LICENSE:=GPL-2.0-only
PKG_MAINTAINER:=ImmortalWrt

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
